application: ng-codelab
version: alpha
runtime: python27
threadsafe: true
api_version: 1


libraries:
- name: webapp2
  version: latest


builtins:
# Enables Appstats at /_ah/stats/ when you enable the event recorder.
# Refer appengine_config.py for the wsgi middleware that enables the event
# recorder and
# https://developers.google.com/appengine/docs/python/tools/appengineconfig
- appstats: on
- default: on


handlers:
- url: /favicon.ico
  static_files: client/favicon.ico
  upload: client/favicon.ico

- url: (/|/index.html)
  static_files: client/index.html
  upload: client/index.html

- url: /api/.*
  script: app.wsgi_app

- url: /(.*\.(js|css|html))
  static_files: client/\1
  upload: client/(.*\.(js|css|html))

skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# Skip spec files
- ^client/.*spec\.*js
